Remove add suggestion with custom flag
vishwasraj-thyagaraj/ember-power-select pull request #10
Opened 2022-06-23 13:38 UTC by vishwasraj-thyagaraj

2022-07-07 14:57 UTC, vigneshk-fd commented on addon/components/power-select.js
> +        if(this.get('multiSelect') && this.get('allowCommaSeparatedValues') && this.get('publicAPI.text') && !this.get('publicAPI.highlighted')) {
Can we refactor to add a few more variables and reduce cognitive load on the `if` condition readability ?

2022-07-07 14:59 UTC, vigneshk-fd commented on addon/components/power-select.js
> +          this.get('onchange')({ __isSuggestion__: true, __value__: get(event, 'target.value') }, this.get('publicAPI'), event);
Lines 471 & 464 --> seems to perform the same functionality with same syntax, can we refactor with a common method, for simplicity ? so that the `__x__` variables doesn't look odd when glanced at first instance.

2022-07-07 15:00 UTC, vigneshk-fd commented on addon/components/power-select.js
> +      run.next(() => input && document.activeElement !== input && input.focus());
```suggestion
     input &&  run.next(() => document.activeElement !== input && input.focus());
```
Let's not queue an action to runloop at all, when there is not input element present.

2022-07-07 15:00 UTC, vigneshk-fd requested changes
Changes requested

2022-07-07 19:00 UTC, vishwasraj-thyagaraj commented on addon/components/power-select.js
> +        if(this.get('multiSelect') && this.get('allowCommaSeparatedValues') && this.get('publicAPI.text') && !this.get('publicAPI.highlighted')) {
can reduce to this, but would not look much readable. Is that okay?

```
if(this.get('allowCreateOnBlur') && this.get('multiSelect') && this.get('allowCommaSeparatedValues') && this.get('publicAPI.text') && !this.get('publicAPI.highlighted')) {
  this.get('publicAPI.text').split(',').forEach(str => {
    str = str.trim();
    if(isPresent(str)) {
      this.get('onchange')([{ __isSuggestion__: true, __value__: str }], this.get('publicAPI'), event);
    }
  });
  this.updateState({ text: '' });
} else if(this.get('allowCreateOnBlur') && !this.get('multiSelect') && get(event, 'target.value')) {
  this.get('onchange')({ __isSuggestion__: true, __value__: get(event, 'target.value') }, this.get('publicAPI'), event);
}
```

2022-07-07 19:12 UTC, vishwasraj-thyagaraj commented on addon/components/power-select.js
> +          this.get('onchange')({ __isSuggestion__: true, __value__: get(event, 'target.value') }, this.get('publicAPI'), event);
```
onBlur(event) {
  if(this.get('multiSelect') && this.get('allowCommaSeparatedValues') && this.get('publicAPI.text') && !this.get('publicAPI.highlighted')) {
    this.get('publicAPI.text').split(',').forEach(str => {
      this.buildCustomSuggestion(str.trim());
    });
  }

  if(!this.get('multiSelect') && get(event, 'target.value')) {
    this.buildCustomSuggestion(get(event, 'target.value').trim());
  }
},

buildCustomSuggestion(str) {
  let value = { __isSuggestion__: true, __value__: str };
  this.get('onchange')(this.get('multiSelect') ? [value] : value, this.get('publicAPI'), event);
}
```

2022-07-07 19:12 UTC, vishwasraj-thyagaraj commented on addon/components/power-select.js
> +          this.get('onchange')({ __isSuggestion__: true, __value__: get(event, 'target.value') }, this.get('publicAPI'), event);
is this one okay?

2022-07-12 06:09 UTC, vigneshk-fd commented on addon/components/power-select.js
> +        if(this.get('multiSelect') && this.get('allowCommaSeparatedValues') && this.get('publicAPI.text') && !this.get('publicAPI.highlighted')) {
I meant only on the `if` condition @vishwasraj-thyagaraj

2022-07-12 07:51 UTC, vishwasraj-thyagaraj commented on addon/components/power-select.js
> +        if(this.get('multiSelect') && this.get('allowCommaSeparatedValues') && this.get('publicAPI.text') && !this.get('publicAPI.highlighted')) {
done

2022-07-12 08:19 UTC, vigneshk-fd approved these changes

2022-07-22 13:49 UTC, vigneshk-fd approved these changes

2022-07-25 05:46 UTC, merged